
services:
  dailypilot-bot:
    build: .
    container_name: dailypilot-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Старые данные (если есть)
      - db_data:/app/db    # БД
volumes:
  db_data:
    networks:
      - dailypilot_net

networks:
  dailypilot_net:
    driver: bridge
